<?php

namespace DoctrineORMModule\Proxy\__CG__\organiza\V1\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Company extends \organiza\V1\Entity\Company implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'organiza\\V1\\Entity\\Company' . "\0" . 'id', '' . "\0" . 'organiza\\V1\\Entity\\Company' . "\0" . 'fullName', '' . "\0" . 'organiza\\V1\\Entity\\Company' . "\0" . 'cnpj', '' . "\0" . 'organiza\\V1\\Entity\\Company' . "\0" . 'cep', '' . "\0" . 'organiza\\V1\\Entity\\Company' . "\0" . 'logradouro', '' . "\0" . 'organiza\\V1\\Entity\\Company' . "\0" . 'complemento', '' . "\0" . 'organiza\\V1\\Entity\\Company' . "\0" . 'bairro', '' . "\0" . 'organiza\\V1\\Entity\\Company' . "\0" . 'localidade', '' . "\0" . 'organiza\\V1\\Entity\\Company' . "\0" . 'uf', '' . "\0" . 'organiza\\V1\\Entity\\Company' . "\0" . 'dtResgister', '' . "\0" . 'organiza\\V1\\Entity\\Company' . "\0" . 'user'];
        }

        return ['__isInitialized__', '' . "\0" . 'organiza\\V1\\Entity\\Company' . "\0" . 'id', '' . "\0" . 'organiza\\V1\\Entity\\Company' . "\0" . 'fullName', '' . "\0" . 'organiza\\V1\\Entity\\Company' . "\0" . 'cnpj', '' . "\0" . 'organiza\\V1\\Entity\\Company' . "\0" . 'cep', '' . "\0" . 'organiza\\V1\\Entity\\Company' . "\0" . 'logradouro', '' . "\0" . 'organiza\\V1\\Entity\\Company' . "\0" . 'complemento', '' . "\0" . 'organiza\\V1\\Entity\\Company' . "\0" . 'bairro', '' . "\0" . 'organiza\\V1\\Entity\\Company' . "\0" . 'localidade', '' . "\0" . 'organiza\\V1\\Entity\\Company' . "\0" . 'uf', '' . "\0" . 'organiza\\V1\\Entity\\Company' . "\0" . 'dtResgister', '' . "\0" . 'organiza\\V1\\Entity\\Company' . "\0" . 'user'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Company $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFullName($fullName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFullName', [$fullName]);

        return parent::setFullName($fullName);
    }

    /**
     * {@inheritDoc}
     */
    public function getFullName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFullName', []);

        return parent::getFullName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCnpj($cnpj)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCnpj', [$cnpj]);

        return parent::setCnpj($cnpj);
    }

    /**
     * {@inheritDoc}
     */
    public function getCnpj()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCnpj', []);

        return parent::getCnpj();
    }

    /**
     * {@inheritDoc}
     */
    public function setCep($cep = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCep', [$cep]);

        return parent::setCep($cep);
    }

    /**
     * {@inheritDoc}
     */
    public function getCep()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCep', []);

        return parent::getCep();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogradouro($logradouro = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogradouro', [$logradouro]);

        return parent::setLogradouro($logradouro);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogradouro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogradouro', []);

        return parent::getLogradouro();
    }

    /**
     * {@inheritDoc}
     */
    public function setComplemento($complemento = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComplemento', [$complemento]);

        return parent::setComplemento($complemento);
    }

    /**
     * {@inheritDoc}
     */
    public function getComplemento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComplemento', []);

        return parent::getComplemento();
    }

    /**
     * {@inheritDoc}
     */
    public function setBairro($bairro = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBairro', [$bairro]);

        return parent::setBairro($bairro);
    }

    /**
     * {@inheritDoc}
     */
    public function getBairro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBairro', []);

        return parent::getBairro();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalidade($localidade = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalidade', [$localidade]);

        return parent::setLocalidade($localidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalidade', []);

        return parent::getLocalidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setUf($uf = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUf', [$uf]);

        return parent::setUf($uf);
    }

    /**
     * {@inheritDoc}
     */
    public function getUf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUf', []);

        return parent::getUf();
    }

    /**
     * {@inheritDoc}
     */
    public function setContract($contract = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContract', [$contract]);

        return parent::setContract($contract);
    }

    /**
     * {@inheritDoc}
     */
    public function getContract()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContract', []);

        return parent::getContract();
    }

    /**
     * {@inheritDoc}
     */
    public function setDtResgister($dtResgister)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtResgister', [$dtResgister]);

        return parent::setDtResgister($dtResgister);
    }

    /**
     * {@inheritDoc}
     */
    public function getDtResgister()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtResgister', []);

        return parent::getDtResgister();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\organiza\V1\Entity\User $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

}
